## Data Exploration

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Uploading Dataset

In [3]:
import os
os.getcwd()

'/Users/tajania/code/AlcaRmsp/the_laundromat'

In [4]:
csv_path = '/Users/tajania/code/AlcaRmsp/the_laundromat'
csv_path

'/Users/tajania/code/AlcaRmsp/the_laundromat'

In [5]:
import pandas as pd
df=pd.read_csv(os.path.join(csv_path, 'raw_data/data.csv'))
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [6]:
df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [7]:
# check for fraudulent transactions that destinations for TRANSFERS are also originators for CASH_OUT?
# What about in the transaction not been detected?

In [11]:
df.isFraud ==1

0          False
1          False
2           True
3           True
4          False
           ...
6362615     True
6362616     True
6362617     True
6362618     True
6362619     True
Name: isFraud, Length: 6362620, dtype: bool

In [32]:
# check relationship between amount, isFraud, oldBalanceDest and newBalanceDest

df_fraudBalanceDest = df[(df['isFraud'] == 1) & 
                         (df['oldbalanceDest'] == df['newbalanceDest']) & 
                         (df['amount'] != 0)]
print(len(df_fraudBalanceDest)/len(df[df['isFraud']==1]))
print(len(df_fraudBalanceDest)/len(df[df['isFraud']==0]))

0.4955558261293072
0.000640500364550146

In [34]:

df_fraudBalanceOrig = df[(df['isFraud'] == 1) & 
                         (df['oldbalanceOrg'] == df['newbalanceOrig']) & 
                         (df['amount'] != 0)]
print(len(df_fraudBalanceOrig)/len(df[df['isFraud']==1]))
print(len(df_fraudBalanceOrig)/len(df[df['isFraud']==0]))

0.00499208571776452
6.452214974583781e-06

this shows that 49.5% of the fraudulent transactions have the characteristics of old balance and new balance equal while the amount is different than zero vs 0.6% for non fraudulent transactions

In [33]:
df['realbalanceOrig']=df['newbalanceOrig'] + df['amount'] - df['oldbalanceOrg']
df['realbalanceDest']=df['newbalanceDest'] + df['amount'] - df['oldbalanceDest']
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,realbalanceOrig,realbalanceDest
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0,0.0,9839.64
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0,0.0,1864.28
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0,0.0,181.00
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0,0.0,-21001.00
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0,0.0,11668.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0,0.0,679364.26
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0,0.0,6311409.28
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0,0.0,12622818.55
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0,0.0,850002.52
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0,0.0,1700005.04

In [31]:
#Checking correlation between
df.corr()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,realbalanceOrig,realbalanceDest
step,1.000000,0.022373,-0.010058,-0.010299,0.027665,0.025888,0.031578,0.003277,0.020516,0.010707
amount,0.022373,1.000000,-0.002762,-0.007861,0.294137,0.459304,0.076688,0.012295,0.970660,0.948028
oldbalanceOrg,-0.010058,-0.002762,1.000000,0.998803,0.066243,0.042029,0.010154,0.003835,0.050502,-0.053157
newbalanceOrig,-0.010299,-0.007861,0.998803,1.000000,0.067812,0.041837,-0.008148,0.003776,0.056897,-0.059847
oldbalanceDest,0.027665,0.294137,0.066243,0.067812,1.000000,0.976569,-0.005885,-0.000513,0.304256,0.268997
newbalanceDest,0.025888,0.459304,0.042029,0.041837,0.976569,1.000000,0.000535,-0.000529,0.458750,0.463858
isFraud,0.031578,0.076688,0.010154,-0.008148,-0.005885,0.000535,1.000000,0.044109,-0.011283,0.050119
isFlaggedFraud,0.003277,0.012295,0.003835,0.003776,-0.000513,-0.000529,0.044109,1.000000,0.012183,0.005305
realbalanceOrig,0.020516,0.970660,0.050502,0.056897,0.304256,0.458750,-0.011283,0.012183,1.000000,0.908281
realbalanceDest,0.010707,0.948028,-0.053157,-0.059847,0.268997,0.463858,0.050119,0.005305,0.908281,1.000000

In [ ]:
# drop additional unused columns 
X['']

In [ ]:
# binary encoding of label data "type"

In [ ]:
# Imputation of missing data

In [ ]:
# Features engineering
features=['type',...]

In [ ]:
# Define X and y

X=df_preprocessed.drop['columns1','Columns2']
Y=df_preprocessed['isFraud']

In [ ]:
# data split between training and test set 80:20 ratio
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X, Y, test_size = 0.2, \
                                                random_state = randomState)

In [ ]:
#Check if data is balanced

In [ ]:
#Oversampling data with SMOTE because there are very few cases of Fraud
sudo pip install imbalanced-learn

from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy='minority')
X_train, y_train = sm.fit_resample(X_train, y_train.ravel())

In [ ]:
#Check if data is balanced with SMOTE